---
- name: deploy app
  hosts: server
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
    - setup_docker
    - setup_app
    # - setup_nginx
    # - setup_prometheus
