---
- name: install nginx
  become: true
  apt:
    name: nginx
    state: present

- name: copy cert
  copy:
    src: certi.crt
    dest: /etc/ssl/certi.crt
    backup: yes

- name: copy key
  copy:
    src: certi.key
    dest: /etc/ssl/certi.key
    backup: yes

- name: copy nginx confi
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    backup: yes

- name: restart nginx
  become: true
  service:
    name: nginx
    state: restarted
