version: 2.1

jobs:
  configure-server:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "3a:c5:42:5d:8d:4f:0f:18:71:82:5b:a4:a4:3b:9b:1a"
      - run:
          name: install ansible, tar and gzip
          command: |
            apk add --update ansible
            apk add --no-cache tar gzip
      - run:
          name: compress files and move folder
          command: |
            tar -C ./src -czvf artifact.tar.gz .
            mkdir .circleci/ansible/roles/setup_app/files/
            mv artifact.tar.gz .circleci/ansible/roles/setup_app/files/artifact.tar.gz
      - run:
          name: run ansible playbook
          command: |
            cd .circleci/ansible
            ansible-playbook -i inventory.txt main.yml
workflows:
  default:
    jobs:
      - configure-server
