---
- name: create directory
  file:
    path: ~/ubuntu-conference-app
    state: directory

- name: copy app zipped folder
  become: yes
  copy:
    src: artifact.tar.gz
    dest: ~/ubuntu-conference-app/artifact.tar.gz
    mode: "0755"
    recurse: yes

- name: Install tar and gzip
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - tar
    - gzip

- name: change working directory
  shell: |
    cd ~/ubuntu-conference-app

- name: run the app
  shell: |
    docker-compose up -d
