---
- name: create directory
  file:
    path: ~/ubuntu-conference-app
    state: directory

- name: copy app zipped folder
  copy:
    src: artifact.tar.gz
    dest: ~/ubuntu-conference-app/artifact.tar.gz
    backup: yes

- name: Install tar and gzip
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - tar
    - gzip

- name: extract and run app
  shell: |
    cd ~/ubuntu-conference-app
    tar -xvzf artifact.tar.gz
    ls
    source env.sh
    docker-compose down
    docker-compose up --build -d
