version: '3.3'
services:
  db:
   restart: always
   image: mysql:latest
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: ${APP_PASSWORD}
  webapp:
   depends_on:
     - db
   build:
     context: ./
     dockerfile: dockerfile
   ports:
     - "8000:8000"
   environment:
     APP_PASSWORD: ${APP_PASSWORD}
     APP_USERNAME: ${APP_USERNAME}
     APP_SERVERNAME: ${APP_SERVERNAME}
     APP_DATABASENAME: ${APP_DATABASENAME}